import streamlit as st
st.title("Probando una GUI con streamlit (WebGUI)")
st.write ("Escribiendo un texto de ejemplo....")
st.header("Cabecera")
st.markdown("Texto reducido")
st.subheader("Subcabecera")
st.caption("Texto tipo leyenda")
st.code("x=2022")
st.latex(r''' 10+2 x^1+3 x^2-6 x^3 ''')
st.image("casa.jpg")
st.audio("intro.mp3")
st.video("olas.mp4")
st.checkbox('Elige esta opción si quieres.')
st.button('Click')
st.radio('Elige género:',['Hombre','Mujer'])
st.selectbox('Elige género:',['Hombre','Mujer'])
st.multiselect('Elige provincia',['A Coruña', 'Lugo', 'Orense','Pontevedra'])
st.select_slider('Escoge una opción', ['Malo', 'Bueno', 'Excelente'])
st.slider('Elige un múmero', 0,100)
st.number_input('Elige un múmero', 0,10)
st.text_input('Email')
st.date_input('Escoge una fecha')
st.time_input('Escoge una hora')
st.text_area('Descripción')
st.file_uploader('Subir un archivo')
st.color_picker('Elegir un color')
import time
with st.spinner('Esperando 2 segundos...'):
    time.sleep(2)
st.progress(10)
st.success("Tiempo transcurrido !")
st.error("Error")
st.warning("Aviso!")
st.info("Esto es un mensaje de información")
st.exception(RuntimeError("RuntimeError exception"))
st.snow()
